server:
  port: 8080
  tomcat:
    max-threads: 500
    accept-count: 1234567
    max-connections: 10000
  undertow:
    io-threads: 10
    worker-threads: 20

spring:
  application:
    name: springboot
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 2000
